apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
            - name: sqlserver
              containerPort: 1433
          env:
          - name: SA_PASSWORD
            value: "123qweX."
          - name: ACCEPT_EULA
            value: "Y"